title: Actually good UI Designs
timezone: Europe/Zurich
collections:
  posts:
    title: Posts
    output: true
  steps:
    title: Steps
    output: false
  uploads:
    title: Uploads
    output: true
  tags:
    title: Tags
    output: true
  authors:
    title: Authors
    output: false
defaults:
- scope:
    path: ''
    type: steps
  values:
    title: 
    date: 2016-09-01 00:00:00 -0700
markdown: kramdown
highlighter: rouge
lsi: false
description: Some actual eye-candy for you to enjoy.
baseurl: ""
url: https://actually.hasgoodui.design
color: "#0d1117"

github-repo: 'Actually-good-UI'

footer-description: Website listing some actual good UI designs made by other sites, services and alike.

plugins:
  - github-pages
  - jekyll-octicons
  - tzinfo-data